name: lidar-fit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.7.*
  - numpy>=1.24
  - pandas>=2.0
  - xarray>=2023.1
  - scipy>=1.10
  - netcdf4>=1.6
  - pip
  - pip:
      - requests>=2.31
